name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, v14.17, 16.x, '*']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install --no-package-lock
      - run: npm test